auto-pickup:
  enabled: true
  blacklist:
    - '*ore'
  replace:
    - 'STONE:COBBLESTONE'
blacklisted-worlds:
  - 'world_nether'
blocks-prices:
  SANDSTONE:1: 0.1
first-join-commands:
  - 'msg hello %player%'